const NFT_LISTING_STATE = {
  NOT_LISTED: 'NOT_LISTED',
  FOR_SALE: 'FOR_SALE',
  IN_AUCTION: 'IN_AUCTION'
};

const COMPLETE_LISTING_STATUS = {
  SUCCESS: 'SUCCESS',
  IN_PROGRESS: 'IN_PROGRESS',
  FAILED: 'FAILED',
  INACTIVE: 'INACTIVE'
};

export {
  NFT_LISTING_STATE,
  COMPLETE_LISTING_STATUS
};
