const NFT_LISTING_STATE = {
  NOT_LISTED: 'NOT_LISTED',
  FOR_SALE: 'FOR_SALE',
  IN_AUCTION: 'IN_AUCTION'
};

const NFT_MODALS = {
  LIST: 'LIST',
  UNLIST: 'UNLIST',
  CHANGE_PRICE: 'CHANGE_PRICE',
  BUY_NOW: 'BUY_NOW',
  MAKE_OFFER: 'MAKE_OFFER',
  PLACE_BID: 'PLACE_BID'
};

const TRANSACTION_STATUS = {
  SUCCESS: 'SUCCESS',
  IN_PROGRESS: 'IN_PROGRESS',
  FAILED: 'FAILED',
  INACTIVE: 'INACTIVE'
};

export {
  NFT_LISTING_STATE,
  NFT_MODALS,
  TRANSACTION_STATUS
};
